import { app, page, route } from "@wasp.sh/spec";
import { App } from "./src/App" with { type: "ref" };
import { LoginPage } from "./src/auth/email/LoginPage" with { type: "ref" };
import { SignupPage } from "./src/auth/email/SignupPage" with { type: "ref" };
import { userSignupFields } from "./src/auth/email/userSignupFields" with { type: "ref" };
import { tagsSpec } from "./src/tags/tags.wasp";
import { tasksSpec } from "./src/tasks/task.wasp";

// The Wasp "basic" template with one change for a hosting guide: username + password
// auth instead of email auth, so the server needs no email provider (SMTP/SendGrid)
// to run in production. Everything else is the template as generated by `wasp new`.
export default app({
  name: "waspOnSnapdeploy",
  wasp: { version: "^0.25.0" },
  title: "wasp-on-snapdeploy",
  head: ["<link rel='icon' href='/favicon.ico' />"],
  auth: {
    userEntity: "User",
    methods: {
      usernameAndPassword: {
        userSignupFields,
      },
    },
    onAuthSucceededRedirectTo: "/",
    onAuthFailedRedirectTo: "/login",
  },
  client: {
    rootComponent: App,
  },
  spec: [
    tasksSpec,
    tagsSpec,
    route("LoginRoute", "/login", page(LoginPage)),
    route("SignupRoute", "/signup", page(SignupPage)),
  ],
});
